---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api-sample
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-api-sample
    spec:
      containers:
        - name: backend
          image: nj93/node-api-sample
          ports:
            - name: http
              containerPort: 3000

apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-mapping-1661101112508
  namespace: default
spec:
  service: quote.default:80
  timeout_ms: 3000
  connect_timeout_ms: 3000
  retry_policy:
    retry_on: 5xx
    num_retries: 1
    per_try_timeout: 0.150s
  hostname: '*'
  prefix: /quote/
  docs:
    path: /.ambassador-internal/openapi-docs
