apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: node-api-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api-sample
  strategy:
    canary:
      canaryService: node-api-sample-canary
      stableService: node-api-sample
      steps:
        - setWeight: 10
        - pause:
            duration: 10
      trafficRouting:
        ambassador:
          mappings:
            - node-api-sample
  template:
    metadata:
      labels:
        app: node-api-sample
    spec:
      containers:
        - args:
          image: nj93/node-api-sample:v2
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 3000
          resources: {}
